"""add_agent_preset_table

Revision ID: 51a39bf1d4af
Revises: d097ffee292c
Create Date: 2026-03-01 14:46:28.465398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a39bf1d4af'
down_revision: Union[str, None] = 'd097ffee292c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_presets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('persona_description', sa.String(), nullable=False),
    sa.Column('expertise', sa.String(), nullable=False),
    sa.Column('suggested_model', sa.String(), nullable=False),
    sa.Column('llm_provider', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_presets')
    # ### end Alembic commands ###
